# Generated by Django 5.1.7 on 2025-03-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("manager", "Manager")],
                default="manager",
                max_length=20,
            ),
        ),
    ]
