# Generated by Django 5.1.7 on 2025-03-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
