# Generated by Django 5.1.7 on 2025-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supermarket_location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='supermarket_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
