# Generated by Django 5.1.7 on 2025-03-14 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_supermarket_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supermarket_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supermarket_name',
        ),
        migrations.AddField(
            model_name='order',
            name='supermarket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.supermarket'),
        ),
    ]
