# Generated by Django 5.1.7 on 2025-03-14 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_supermarket_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supermarket',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.supermarket'),
        ),
    ]
