# Generated by Django 5.1.7 on 2025-03-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_supermarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supermarket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.supermarket'),
        ),
    ]
