# Generated by Django 5.1.7 on 2025-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_supermarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Loading', 'Loaded'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
