# Generated by Django 5.1.7 on 2025-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Loaded', 'Loaded'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
