# Generated by Django 5.1.7 on 2025-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_date',
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='factory_name',
            field=models.CharField(default='Default Factory', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='products',
            field=models.ManyToManyField(through='shipment.ShipmentItem', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
